/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    get: {
      responses: {
        /** OK */
        200: unknown
      }
    }
  }
  '/recipes': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.recipes.id']
          created_at?: parameters['rowFilter.recipes.created_at']
          created_by?: parameters['rowFilter.recipes.created_by']
          /** Name of recipe */
          name?: parameters['rowFilter.recipes.name']
          /** URL for the recipe image */
          image?: parameters['rowFilter.recipes.image']
          /** URL for the recipe */
          url?: parameters['rowFilter.recipes.url']
          /** Filtering Columns */
          select?: parameters['select']
          /** Ordering */
          order?: parameters['order']
          /** Limiting and Pagination */
          offset?: parameters['offset']
          /** Limiting and Pagination */
          limit?: parameters['limit']
        }
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range']
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit']
          /** Preference */
          Prefer?: parameters['preferCount']
        }
      }
      responses: {
        /** OK */
        200: {
          schema: definitions['recipes'][]
        }
        /** Partial Content */
        206: unknown
      }
    }
    post: {
      parameters: {
        body: {
          /** recipes */
          recipes?: definitions['recipes']
        }
        query: {
          /** Filtering Columns */
          select?: parameters['select']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** Created */
        201: unknown
      }
    }
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.recipes.id']
          created_at?: parameters['rowFilter.recipes.created_at']
          created_by?: parameters['rowFilter.recipes.created_by']
          /** Name of recipe */
          name?: parameters['rowFilter.recipes.name']
          /** URL for the recipe image */
          image?: parameters['rowFilter.recipes.image']
          /** URL for the recipe */
          url?: parameters['rowFilter.recipes.url']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.recipes.id']
          created_at?: parameters['rowFilter.recipes.created_at']
          created_by?: parameters['rowFilter.recipes.created_by']
          /** Name of recipe */
          name?: parameters['rowFilter.recipes.name']
          /** URL for the recipe image */
          image?: parameters['rowFilter.recipes.image']
          /** URL for the recipe */
          url?: parameters['rowFilter.recipes.url']
        }
        body: {
          /** recipes */
          recipes?: definitions['recipes']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
  }
}

export interface definitions {
  recipes: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string
    /** Format: uuid */
    created_by?: string
    /**
     * Format: text
     * @description Name of recipe
     */
    name: string
    /**
     * Format: text
     * @description URL for the recipe image
     */
    image?: string
    /**
     * Format: text
     * @description URL for the recipe
     */
    url: string
  }
}

export interface parameters {
  /** @description Preference */
  preferParams: 'params=single-object'
  /** @description Preference */
  preferReturn: 'return=representation' | 'return=minimal' | 'return=none'
  /** @description Preference */
  preferCount: 'count=none'
  /** @description Filtering Columns */
  select: string
  /** @description On Conflict */
  on_conflict: string
  /** @description Ordering */
  order: string
  /** @description Limiting and Pagination */
  range: string
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string
  /** @description Limiting and Pagination */
  offset: string
  /** @description Limiting and Pagination */
  limit: string
  /** @description recipes */
  'body.recipes': definitions['recipes']
  /** Format: bigint */
  'rowFilter.recipes.id': string
  /** Format: timestamp with time zone */
  'rowFilter.recipes.created_at': string
  /** Format: uuid */
  'rowFilter.recipes.created_by': string
  /**
   * Format: text
   * @description Name of recipe
   */
  'rowFilter.recipes.name': string
  /**
   * Format: text
   * @description URL for the recipe image
   */
  'rowFilter.recipes.image': string
  /**
   * Format: text
   * @description URL for the recipe
   */
  'rowFilter.recipes.url': string
}

export interface operations {}

export interface external {}
